name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: website

    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.NAME }}
    - run: npm install
    - run: npm run deploy
      env:
        GIT_USER: ${{ github.actor }}:${{ github.token }}
